HW 13.08 Reading employee from HTTP
IlyaZakharchenko/ABDProjects pull request #1
Opened 2020-08-18 11:08 UTC by IlyaZakharchenko

2020-08-19 10:33 UTC, R00We requested changes
Ревью завершил, есть замечания.

2020-08-19 10:33 UTC, R00We commented on src/parser/FileEmployeeParser.java
> +            } catch (WrongFileFormatException e) {
Зачем отлавливать только что выброшенное исключение?

2020-08-19 10:33 UTC, R00We commented on src/parser/FileEmployeeParser.java
> +        }
В место констант предлагаю использовать имя класса. Его можно получиться вызвав у любого объекта getClass().getSimpleName()

2020-08-19 10:33 UTC, R00We commented on src/model/HourEmployee.java
> +        return 20.8 * 8 * payment;
`20.8 * 8` предлагаю вынести в приватную константу

2020-08-19 10:33 UTC, R00We commented on src/parser/FileEmployeeParser.java
> +    protected final String SEPARATOR = "|";
Т.к. сепаратор используется как для записи так и для чтения то предлагаю вынести его в отдельный класс которым будут пользоваться обе сущности

2020-08-19 10:33 UTC, R00We commented on src/parser/FileEmployeeParser.java
> +        str += employee.getId() + SEPARATOR + employee.getName() + SEPARATOR + employee.calculatePayment();
в файл записывается результат выполнения метода `calculatePayment()` т.е. зп за месяц работы. А при создании сотрудника требуется стоимость часа работы.

2020-08-19 10:33 UTC, R00We commented on src/reader/FileEmployeeReader.java
> +    private final FileEmployeeParser PARSER = new FileEmployeeParser();
1) Парсер нада прокидывать в конструкторе. Тем самым с реализации ридера снимется ответственность за выбор парсера.
2) Парсер должен предоставляться в виде интерфейса. Иначе зачем вы вообще его заводили

2020-08-19 10:33 UTC, R00We commented on src/Main.java
> +    }
Предлагаю сортировку реализовать в отдельном классе который будет расширять интерфейс `Comparator`

2020-08-19 10:33 UTC, R00We commented on src/reader/HttpEmployeeReader.java
> +        }
Во всех местах где могут произойти исключения они в этом же файле перехватываются и "глушатся". Т.е. клиент данного класса никогда не узнает что во время работы произошли ошибки. Это плохой подход. Предлагаю не отлавливать исключения и переложить эти действия вызывающих методы.

2020-08-20 13:05 UTC, IlyaZakharchenko commented on src/parser/FileEmployeeParser.java
> +    protected final String SEPARATOR = "|";
Но ведь сепаратор используется только в парсере

2020-08-22 11:03 UTC, R00We approved these changes
Принимаю

2020-08-22 11:04 UTC, merged